version: '2.2'

services:
  web:
    build: ./dashboard
    volumes:
        - static_volume:/usr/src/dashboard/web/server/build
    expose:
        - 443
        # - 5432
    restart: always
 
  nginx:
    build: ./nginx
    volumes:
        - static_volume:/usr/src/dashboard/web/server/build
    ports:
        - 443:443
        - 80:80
        # - 5432:5432

    environment:
      # - SERVER_NAME=54.87.227.198
      - SERVER_NAME=0.0.0.0

    restart: always
    depends_on:
        - web

    

volumes:
  static_volume:   


   
        